### ISSUE TITLE
Error creating resource -- Missing MCrypt

### ISSUE THREAD

**Issue by mikeerickson** [gnarula/sublime-laravelgenerator#24]
Hey there

When I attempt to use the Sublime Generator plugin, I receive an error "Oh snap... MCrypt required"

I am pretty sure this is installed as I am able to use the generator just fine from within terminal?   

Recommendations?

**Comment by gnarula** [comment]
Is the php binary being executed the same in both cases? Try executing
`which php` in the command line and setting the same path in the config.

**Comment by mettjus** [comment]
The problem is due to the instance of php used to run the command.
Jeffrey Way suggested:
- browse packages folder
- make a copy of "Laravel Generator/laravelgenerator.sublime-settings" to "User/laravelgenerator.sublime-settings" to avoid override on package updates
- edit "User/laravelgenerator.sublime-settings" and specify the path to the most recent version of php in the "php_path" property
  It solved the problem for me (working on Mac).

**Comment by gnarula** [comment]
In case this isn't solved yet, PHP from http://php-osx.liip.ch/ has MCrypt compiled. Use the binary provided from there and you should be fine.
